# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5-stretch

    working_directory: /go/src/transport

    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Run Unit Tests
          command: |
            chmod +x .circleci/circleScripts.sh
            ./.circleci/circleScripts.sh test

      - run:
          name: Deploy Changed Services to Azure
          command: |
            ./.circleci/circleScripts.sh deploy
