START_REGISTRATION = "startRegistration"
REGISTRATION_SUCCESS = "registrationSuccess"
ROUTE_REQUEST = "routeRequest"
ASSIGN_ROUTE = "assignRoute"
METRICS_UPLOAD = "metricsUpload"
ROUTE_COMPLETE = "routeComplete"
TRAINING_COMPLETE = "trainingComplete"
PARAMETER_SET_UPLOAD = "paramSetUpload"